id: P006976
initial_creation_type: ocr
source_metadata:
  id: bdr:W28885
  title: ཐང་རྒྱལ་རབས་ཀྱི་སྙན་ཚིག་ཁག་སུམ་བརྒྱ
  author: ''
  volumes:
    11849bf91e794ac8a79edd691f6729cc:
      image_group_id: I4859
      title: ''
      volume_number: 1
      total_pages: 482
      base_file: v001.txt
ebook_metadata:
  title: ཐང་རྒྱལ་རབས་ཀྱི་སྙན་ཚིག་ཁག་སུམ་བརྒྱ
  author: ''
  sku: P006976
  cover: cover.jpg
  layers:
  - pagination
